name: Upgrade to latest CDK version (v2)
on:
  schedule:
    - cron:  '0 4 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v1
      - name: Run upgrade script
        id: 'release_version'
        run: npm run upgrade-cdk -- 1
