name: upgrade-cdk
on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 4 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Run upgrade script
        id: 'upgrade_cdk_script'
        run: npm run upgrade-cdk
